---

- id: elisp-check-parens
  name: elisp-check-parens
  entry: hooks/elisp-check-parens.py
  language: script
  files: \.el$

- id: elisp-check-byte-compile
  name: elisp-check-byte-compile
  entry: hooks/elisp-check-byte-compile.py
  language: script
  files: \.el$

- id: elisp-byte-compile
  name: elisp-byte-compile
  entry: hooks/elisp-byte-compile.py
  language: script
  files: \.el$

- id: elisp-check-native-compile
  name: elisp-check-native-compile
  entry: hooks/elisp-check-native-compile.py
  language: script
  files: \.el$

- id: elisp-native-compile
  name: elisp-native-compile
  entry: hooks/elisp-native-compile.py
  language: script
  files: \.el$

- id: elisp-indent
  name: elisp-indent
  entry: hooks/elisp-indent.py
  language: script
  files: \.el$
