---

- id: elisp-check-parens
  name: elisp-check-parens
  entry: hooks/elisp-check-parens.sh
  language: script
  files: \.el$

- id: elisp-byte-compile
  name: elisp-byte-compile
  entry: hooks/elisp-byte-compile.sh
  language: script
  files: \.el$

- id: elisp-indent
  name: elisp-indent
  entry: hooks/elisp-indent.sh
  language: script
  files: \.el$
